### PR TITLE
Do not hardcode python version. Assume there's gonna be only one FIXM…

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
Assume there's gonna be only one FIXME if not.

This should prevent failure when python version is updated. 

Coming from https://github.com/ansible/ansible-hub-ui/pull/639#issuecomment-881044037

### CODE REVIEW

**Comment by himdel** [comment]
Code changes look good, but cypress was using a cached container so it never tried to build your version.

Can you temporarily add something like...

```diff
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -39,7 +39,7 @@ jobs:
       uses: actions/cache@v2
       with:
         path: pulp_galaxy_ng/image
-        key: ${{ runner.os }}-container-${{ env.GALAXY_NG_COMMIT }}
+        key: x${{ runner.os }}-container-${{ env.GALAXY_NG_COMMIT }}
 
     - name: "Build pulp-galaxy-ng"
       if: steps.cache-container.outputs.cache-hit != 'true'
```

wait for cypress to run, link to the run, and remove it again?

**Review by himdel — APPROVED** [review]
LGTM, it built just fine in https://github.com/ansible/ansible-hub-ui/pull/642/checks?check_run_id=3124388480#step:6:34 :+1: 

(Don't forget to remove the `key: x` change.)

**Comment by webknjaz** [comment]
@himdel did you know you can add the backport labels before merging? In this case, patchback still processes them after the merge.

**Comment by himdel** [comment]
(Oh well, I tried :) The whitespace changes cause conflicts for the bot.
Removing, we stable-4.3 is staying with python3.6 for now anyway.)

**Pull request merged**
