### PR TITLE
EE Detail page tab Images - fix cards to have proper spacing

### PR DESCRIPTION
**Pull request by MilanPospisil**
https://issues.redhat.com/browse/AAH-1115

Problem Description: EE Detail page tab Images click at any sha of n image - fix cards to have proper spacing

QA Criteria: EE Detail page tab Images - Cards have proper spacing between headers and content. See https://www.patternfly.org/v4/components/card/ for reference.

Proposed Solution: See https://www.patternfly.org/v4/components/card/  Use CardTitle and CardBody.

### CODE REVIEW

**Comment by MilanPospisil** [comment]
TODO - screenshoots :)

**Comment by awcrosby** [comment]
(adding this to a few recently updated PRs…) We need CI in this repo that enforces this, but for now please:
* Add a line to at least one of your commits that says `Issue: AAH-####` (in the future it is best to be the first commit as it gets included in the initial PR description by default)
* Ensure when merging that the `Issue: AAH-####` is part of commit message via the “Squash ‘n’ Merge” description

**Comment by MilanPospisil** [comment]
Before:
EEDetailImagesBefore
After:
EEDetailImagesAfter

**Comment by ZitaNemeckova** [comment]
@MilanPospisil Remove `<section className='body'>`, please. It's adding extra padding.

**Review by himdel — APPROVED** [review]

**Pull request merged**
