### PR TITLE
[rbac] Role lists - default sort by name, show description, pretty "Galaxy only" in AppliedFilters

### PR DESCRIPTION
**Pull request by himdel**
Depends on https://github.com/pulp/pulpcore/issues/2703 for the sort to work => https://github.com/pulp/pulpcore/pull/2766 => https://github.com/ansible/galaxy_ng/pull/1279 => just the [branch](https://github.com/ansible/galaxy_ng/commits/feature/rbac-roles) now.

Prettify the "galaxy only" filter indicator in role list:

And make sure role lists are sorting by name everywhere by default, and showing the description where possible.

Current state:

* User Access > Roles
  * has description, locked/unlocked, expandable
  * sort by name works, not default => **made `name` default**
* User Access > Groups > detail
  * tab Access
    * just name, expandable => **added `description`, use permission data already available (since pulp 3.20)**
    * sort by name broken, not default => **it is default, indicator has problems because the tabs share state (for later), api should work after https://github.com/pulp/pulpcore/issues/2703 + removed the `sort` -> `ordering` logic from `GroupRoleAPI` .. then reenabled after https://github.com/pulp/pulpcore/pull/2849**
  * tab Access, modal Add roles
    * has description, (not expandable)
    * sort by name works, default but doesn't indicate it => **fixed**
* Collections > Namespaces > detail
  * tab Namespace owners, modal Select a group (step 2)
    * has description, (not expandable)
    * sort by name works, default but doesn't indicate it => **fixed**
  * tab Namespace owners > group detail
    * just name, expandable (permissions & description lazy loaded when expanding)
    * no sort => **sorting in ui, just by name**
  * tab Namespace owners > group detail, modal Add roles
    * has description, (not expandable)
    * sort by name works, default but doesn't indicate it => **fixed**
* Execution Environments > Execution Environments > detail
  * tab Owners, modal Select a group (step 2)
    * has description, (not expandable)
    * sort by name works, default but doesn't indicate it => **fixed**
  * tab Owners > group detail
    * just name, expandable (permissions & description lazy loaded when expanding)
    * no sort => **sorting in ui, just by name**
  * tab Owners > group detail, modal Add roles
    * has description, (not expandable)
    * sort by name works, default but doesn't indicate it => **fixed**

### CODE REVIEW

**Comment by MilanPospisil** [comment]
User Access -> Roles. In the table, there is column Locked, while in the filter drop down, it is named as Status, which looks confusing to me. Is it really what it was desired?

**Comment by MilanPospisil** [comment]
When Galaxy only filter is closed, it cant be set again (only by reloading) - is this supposed behavior?

**Comment by MilanPospisil** [comment]
tab Namespace owners, modal Select a group (step 2) -  has description, (not expandable)
tab Owners, modal Select a group (step 2) - has description, (not expandable).

This does not seems to be true, I dont see any description in group selections. Anyway, groups have no description at all.

**Comment by himdel** [comment]
> User Access -> Roles. In the table, there is column Locked, while in the filter drop down, it is named as Status, which looks confusing to me. Is it really what it was desired?

Good catch, we were supposed to rename this to "built-in"/"editable" to make the meaning clear... updating.

**Comment by himdel** [comment]
> When Galaxy only filter is closed, it cant be set again (only by reloading) - is this supposed behavior?

Yeaah, kinda .. it is consistent with Approval Dashboard's Status: Needs Review filter.
So, it's the behaviour we have, but eventually we should come up with a better UI for default filters.

The idea is that the user should almost never care about non-galaxy roles, but we still want to make it possible to see the rest, on this screen only.

**Comment by himdel** [comment]
> tab Namespace owners, modal Select a group (step 2) - has description, (not expandable)
> tab Owners, modal Select a group (step 2) - has description, (not expandable).
>
> This does not seems to be true, I dont see any description in group selections. Anyway, groups have no description at all.

Hence *step 2* :) - step 1 is groups, step 2 is roles.

**Review by MilanPospisil — APPROVED** [review]
LGTM :+1:

**Pull request merged**
