### PR TITLE
Delete registries, add registries, edit, view registries test.

### PR DESCRIPTION
**Pull request by MilanPospisil**
Test for Execution enviroments -> Remote Registries. It tests addition of new and view of table of registries. It deletes registries before and after to maintain db clean and allow repetition of tests.

### CODE REVIEW

**Review by himdel — APPROVED** [review]
LGTM :+1:

**Comment by himdel** [comment]
(backporting because https://github.com/ansible/ansible-hub-ui/pull/1116 depens on this)

**Comment by MilanPospisil** [comment]
" Ahoj,"



tusis pls co tam delam blbe?



cy.exec('galaxykit -s 'http://localhost:8002/api/automation-hub/' -u admin -
p admin -i collection upload my_namespace my_collection ') failed because 
the command exited with a non-zero code. Pass {failOnNonZeroExit: false} to 
ignore exit code failures. Information about the failure: Code: 1 Stderr: 
Traceback (most recent call last): File "/usr/local/bin/galaxykit", line 10,
in <module> sys.exit(main()) 
 File "/home/milan/.local/lib/python3.7/site-packages/galaxykit/command.py",
line 20.




Prikaz v cypress:

cy.galaxykit('-i collection upload my_namespace my_collection'); 




Diky!
""

**Comment by himdel** [comment]
@MilanPospisil use English please, in any public communication :)
And do read up on escaping code in markdown, the error message is barely readable this way. https://guides.github.com/features/mastering-markdown/
(Also, is this related to this PR at all?)

---

As for what you're doing wrong, the command looks good.

Try running it manually to see what happens, any output?
Also try `pip show galaxykit | grep Version` to see which version you're using, you'll need 0.5.2 or newer.

(And make sure that the UI is actually running on localhost:8002.)

If it's none of those, you can try debugging galaxykit, either by adding logging in galaxykit itself, or by watching the responses with something like `strace -e sendto,recvfrom -s 200  galaxykit -u admin -p admin collection upload`

**Pull request merged**
