### PR TITLE
Fixed group filter

### PR DESCRIPTION
**Pull request by MilanPospisil**
AAH-1846

https://issues.redhat.com/browse/AAH-1846

Depends on: https://github.com/ansible/galaxy_ng/pull/1400 (merged)

It also corrects another icontains missing in /src/containers/group-management/group-list.tsx
Accessible through menu: Execution environments -> select one (EE detail) -> tab Owners -> Select a group button -> filter by name

### CODE REVIEW

**Review by newswangerd — APPROVED** [review]

**Comment by newswangerd** [comment]
I'll get this merged once the api is updated.

**Comment by MilanPospisil** [comment]
> I'll get this merged once the api is updated.

Wait please, I noticed that group_list test is broken. I must repair it according to new changes.

**Comment by himdel** [comment]
This will need a rebase .. the feature/rbac-roles branch has a similar change (https://github.com/ansible/ansible-hub-ui/pull/2336) but with `name_contains`, and sounds like it will get in first.

(We still want `name_icontains` when the api is available.)

**Comment by himdel** [comment]
API is merged now, so this should be ready once the conflict is resolved :)

**Comment by himdel** [comment]
Changes look good, the test failures are caused by ancient backend - should be fixed in #2480.

But also I noticed one more place... `src/components/rbac/select-group.tsx`:

```
63:  if (noData && !filterIsSet(localParams, ['name__contains'])) {
143:                      id: 'name__contains',
156:                niceNames={{ name__contains: t`Name` }}
163:              {noData && filterIsSet(localParams, ['name__contains']) ? (
```

pretty sure that's also a group list view that should have the icontains filter now, can you take care of that one too please? :)

**Review by himdel — APPROVED** [review]

**Pull request merged**
