### PR TITLE
Empty search correct

### PR DESCRIPTION
**Pull request by MilanPospisil**
Compound filter had problem that it accepted blank string (string with only empty spaces). This PR disables filter button in this situation. This corrects the issue for many containers that uses compound filter.

### CODE REVIEW

**Review by ZitaNemeckova — APPROVED** [review]
LGTM 👍

**Comment by himdel** [comment]
4.4 backport: https://github.com/ansible/ansible-hub-ui/pull/1376

**Comment by himdel** [comment]
@MilanPospisil can you please re-check if this works on master?

I think it doesn't:


(or am I testing the wrong thing?)

**Comment by MilanPospisil** [comment]
> @MilanPospisil can you please re-check if this works on master?
> 
> I think it doesn't: 
> 
> (or am I testing the wrong thing?)
> 
> .. More specifically, I think the only difference on master is not being able to click the search button .. but it can still come from searching by pressing enter, and then from the url.
> 
> I think we need to handle at least:
> 
>     * (done) searching by clicking should be disabled for empty search field (or one full of spaces)
> 
>     * searching by enter should not work in empty search field (or one full of spaces)
> 
>     * `AppliedFilters` should never show the empty keywords - it should act as if no filter was present, no Clear all filters either
> 
>     * it should not affect the actual search results (I think this only works in collections now because every collection has a space somewhere in description)
> 
> 
> Ideally we should clear `?keywords=` and `?keywords=%20` from `params` (not just keywords, any such param), and it should not be necessary to change `AppliedFilters` - we don't hide empty params there, we remove them before `AppliedFilters` renders them (but if it turns out you'd have to change every single container, hiding it in `AppliedFilters` might be better), search params are expanded from params in every controller, so we also need to change that before a space lands there, so I _think_ the right place to fix this is `ParamHelper`.


Ok, I did only button disable, I did forgot about enter and URL never come into my mind. I will create new PR and I will do it.

**Comment by MilanPospisil** [comment]
> ### Backport to stable-4.4: 💔 cherry-picking failed — conflicts found
> 
> ❌ Failed to cleanly apply [ee0a93d](https://github.com/ansible/ansible-hub-ui/commit/ee0a93d1959343eae8e8b6f615ef3ba72e773bef) on top of patchback/backports/stable-4.4/ee0a93d1959343eae8e8b6f615ef3ba72e773bef/pr-1195
> ### Backporting merged PR #1195 into master
> 
>     1. Ensure you have a local repo clone of your fork. Unless you cloned it
>        from the upstream, this would be your `origin` remote.
> 
>     2. Make sure you have an upstream repo added as a remote too. In these
>        instructions you'll refer to it by the name `upstream`. If you don't
>        have it, here's how you can add it:
>        ```
>        $ git remote add upstream https://github.com/ansible/ansible-hub-ui.git
>        ```
> 
>     3. Ensure you have the latest copy of upstream and prepare a branch
>        that will hold the backported code:
>        ```
>        $ git fetch upstream
>        $ git checkout -b patchback/backports/stable-4.4/ee0a93d1959343eae8e8b6f615ef3ba72e773bef/pr-1195 upstream/stable-4.4
>        ```
> 
>     4. Now, cherry-pick PR [Empty search correct #1195](https://github.com/ansible/ansible-hub-ui/pull/1195) contents into that branch:
>        ```
>        $ git cherry-pick -x ee0a93d1959343eae8e8b6f615ef3ba72e773bef
>        ```
>        
>        
>            
>              
>            
>        
>              
>            
>        
>            
>          
>        If it'll yell at you with something like `fatal: Commit ee0a93d1959343eae8e8b6f615ef3ba72e773bef is a merge but no -m option was given.`, add `-m 1` as follows intead:
>        ```
>        $ git cherry-pick -m1 -x ee0a93d1959343eae8e8b6f615ef3ba72e773bef
>        ```
> 
>     5. At this point, you'll probably encounter some merge conflicts. You must
>        resolve them in to preserve the patch from PR [Empty search correct #1195](https://github.com/ansible/ansible-hub-ui/pull/1195) as close to the
>        original as possible.
> 
>     6. Push this branch to your fork on GitHub:
>        ```
>        $ git push origin patchback/backports/stable-4.4/ee0a93d1959343eae8e8b6f615ef3ba72e773bef/pr-1195
>        ```
> 
>     7. Create a PR, ensure that the CI is green. If it's not — update it so that
>        the tests and any other checks pass. This is it!
>        Now relax and wait for the maintainers to process your pull request
>        when they have some cycles to do reviews. Don't worry — they'll tell you if
>        any improvements are necessary when the time comes!
> 
> 
> ##
> 
> 🤖 @patchback I'm built with [octomachinery](https://octomachinery.dev) and my source is open — https://github.com/sanitizers/patchback-github-app.

Solving this in:
https://github.com/ansible/ansible-hub-ui/pull/1402

**Pull request merged**
