### PR TITLE
Update to python 3.8 in Cypress workflow

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
Cypress workflow got broken by https://github.com/ansible/galaxy_ng/pull/836

TODO: find a way to prevent it, if possible.

### CODE REVIEW

**Comment by himdel** [comment]
:+1: Fixes ...

```
STEP 4: RUN ln /usr/local/lib/python3.6/site-packages/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf
ln: failed to access '/usr/local/lib/python3.6/site-packages/pulp_ansible/app/webserver_snippets/nginx.conf': No such file or directory
error building at STEP "RUN ln /usr/local/lib/python3.6/site-packages/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf": error while running runtime: exit status 1
time="2021-07-15T19:10:16Z" level=error msg="exit status 1"
Error: Process completed with exit code 1.
```

during the `Build pulp-galaxy-ng` step.

**Comment by himdel** [comment]
> TODO: find a way to prevent it, if possible.

So,
the Containerfile we're using for cypress .. https://github.com/ansible/ansible-hub-ui/blob/master/.github/workflows/cypress.yml#L50-L60
is a fork of the pulp-galaxy-ng image from pulp-oci-images: https://github.com/pulp/pulp-oci-images/blob/latest/pulp_galaxy_ng/Containerfile .

We *could* pull from that repo instead of hardcoding our own version, the repo was updated in https://github.com/pulp/pulp-oci-images/pull/103 so it would have been up to date.

The problem is that the image also hardcodes a couple of versions which are wrong for us:

```diff
-FROM pulp/pulp-ci-centos:latest
+# default podman config on debian doesn't assume docker.io if no registry specified
+FROM docker.io/pulp/pulp-ci-centos:latest

+# we don't need any of these, definitely not galaxy_ng_version
-ARG PULPCORE_VERSION=">=3.11.2,<3.12"
-ARG PULP_CONTAINER_VERSION=">=2.5.2,<2.6"
-ARG PULP_ANSIBLE_VERSION="==0.7.3"
-ARG GALAXY_NG_VERSION="==4.3.1"

 RUN pip3 install --upgrade \
+  "click<8.0" # might no longer be needed?
   requests \
-  pulpcore${PULPCORE_VERSION} \
-  pulp-container${PULP_CONTAINER_VERSION} \
-  pulp-ansible${PULP_ANSIBLE_VERSION} \
-  galaxy-ng${GALAXY_NG_VERSION}
+  git+https://github.com/ansible/galaxy_ng.git@${{ env.SHORT_BRANCH }} # run galaxy master - the point

 RUN ln /usr/local/lib/python3.8/site-packages/pulp_ansible/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_ansible.conf
 RUN ln /usr/local/lib/python3.8/site-packages/pulp_container/app/webserver_snippets/nginx.conf /etc/nginx/pulp/pulp_container.conf
 RUN ln /usr/local/lib/python3.8/site-packages/galaxy_ng/app/webserver_snippets/nginx.conf /etc/nginx/pulp/galaxy_ng.conf
```

So, we may be able to pull that file, run a script to update it for our needs and then use the updated version.
Not sure if that would be more or less brittle than the current though, might be worth trying :)

**Comment by himdel** [comment]
Adding backport-4.3, to fix python version failures in 4.3 .. https://github.com/ansible/ansible-hub-ui/pull/672/checks?check_run_id=3123350899

**Comment by webknjaz** [comment]
Try re-adding the label. I just received a Sentry error notification. Not sure what happened but it seems like `git push` failed.

**Comment by webknjaz** [comment]
Weird, it happened again. I wonder if somebody's been messing with the permissions lately...

**Comment by himdel** [comment]
@webknjaz I hope not, it worked an hour ago in https://github.com/ansible/ansible-hub-ui/pull/672

**Comment by webknjaz** [comment]
It could be a GH problem or they could change something in the permission model. Try another PR to see if it happens again maybe...

**Comment by himdel** [comment]
@webknjaz Seems to be working just fine in https://github.com/ansible/ansible-hub-ui/pull/674, so .. one of those things :)

I can do this one manually, thanks for looking :)

**Comment by webknjaz** [comment]
Please postpone this for 15-30 min, I think I've found the root of the issue. And also I noticed another problem in the code but I want to trigger this flow after the fix once again.

**Comment by himdel** [comment]
No problem :)

**Comment by webknjaz** [comment]
Could you re-apply the label so I could see if I've properly fixed the exception? (there was a silly "tuple doesn't have a replace method" mistake while producing a log message and it wasn't logged properly because of this)

**Comment by webknjaz** [comment]
Urgh.. need another patch. I'll keep you posted.

**Comment by webknjaz** [comment]
Debugging in production be like: Please, retry again... 

After this attempt, hopefully the underlying problem will show up in the bot comment. It is indeed a permission error:
> ! [remote rejected] HEAD -> patchback/backports/stable-4.3/00836c829d0f7851ec451fbf47f388a3bf2603db/pr-639 (refusing to allow a GitHub App to create or update workflow `.github/workflows/cypress.yml` without `workflows` permission)
> To https://github.com/ansible/ansible-hub-ui.git
> error: failed to push some refs to 'https://x-access-token:[Filtered]@github.com/ansible/ansible-hub-ui.git'

**Comment by webknjaz** [comment]
I just want this last test before requesting the proper permission on the App side.

**Comment by webknjaz** [comment]
Ouch... Still, there's a problem. Need another patch.

**Comment by webknjaz** [comment]
@himdel could you relabel once again?

**Comment by himdel** [comment]
Heheh, it's everywhere :) 

And no worries, I too know the pains of debugging these things :)

**Comment by webknjaz** [comment]
I guess I'll stop now. Even though there are more imporovements to do (like making stderr/stdout actually show up), I'll postpone this — the displayed note is useful enough already and I need to switch over to other tasks.
Will ask @gundalow to update the permissions and this should fix it.

**Comment by webknjaz** [comment]
@himdel the permissions are fixed now. If you retry, it should create a backport.

**Comment by himdel** [comment]
Thanks for the update! :)

In the meantime I've found out that we need to stay on python3.6 on that branch for now.
Removing the label.

**Comment by webknjaz** [comment]
Maybe you could trigger it just for the sake of a test (and then close the PR).

**Comment by himdel** [comment]
Ah, sure :) here it goes ^ :)

**Comment by webknjaz** [comment]
> Let me know if you want us to create/find a PR that touches a workflow and _can_ be backported cleanly.

That would be nice, if it's not too much of a hustle :)

**Comment by himdel** [comment]
It may take a bit, but I think we'll be able to try with https://github.com/ansible/ansible-hub-ui/pull/642 once merged, I'll ping you tomorrow :)

**Pull request merged**
