### PR TITLE
[Signing 2] Add sign badge to collection card

### PR DESCRIPTION
**Pull request by brumik**
Screenshot from 2022-02-09 10-38-21
Screenshot from 2022-02-09 10-37-38

### CODE REVIEW

**Comment by himdel** [comment]
| here | before |
|-|-|
|  |  |
|  |  |
|  |  |

**Comment by himdel** [comment]
^ Seems like we get inconsitent card sizing now, and title and company don't get cut off with ellipsis.

Is that something you can fix, or should we just add the badge to the existing cards without changing how they work?

**Comment by himdel** [comment]
I think we can replace this by https://github.com/ansible/ansible-hub-ui/pull/1763 , looks like adding SignatureBadge to the existing CardHeader works fine by itself :)

**Comment by brumik** [comment]
I probably just missed a PF prop on the card. But your PR seems smaller, we can roll with that.

Closing in favour of #1763

**Pull request closed without merging**
