### PR TITLE
First edits for russian locale

### PR DESCRIPTION
**Pull request by dunmaksim**
Hello!

Now I would like to learn more about the review and localization process on the project. Therefore, localization is only partial.

Thanks!

### CODE REVIEW

**Comment by himdel** [comment]
hey :) 
you don't need to commit the changes to `locale/ru.js`, there's weekly automation to update these based on the `.po` files, but since it's a new file, no harm updating it either :)

If you're updating the list of languages in `lingui.config.js`, remember to also update `src/l10n.ts` - the `availableLanguages` array and `languageNames` - that's what the UI uses to actually display anything.

Other than that, looking good, you can also sanity-check the `.po` file by running `lint-po` (from pypi) - `npm run lint:po` does that.

(And also note that anything coming from the API would still be in English, unless you also add the new language to `ansible/galaxy_ng` for the backend.)

(repo tests are currently red, fair warning, actually merging things might take a while)

**Comment by dunmaksim** [comment]
Hello, @himdel !

Me update PR:

* fixed one error in `ru.po` after linting with `npm run lint:po`;
* translated more strings;
* commits squashed.

**Comment by dunmaksim** [comment]
Hello, @himdel !

What I must do for merging this PR into master?

**Comment by himdel** [comment]
Oh, I'm sorry I didn't realize it was ready.. 
the code looks good :+1: thanks!,
kicking the linter workflow...

**Comment by himdel** [comment]
Oh, two things please...

* we have a no merge commits policy, can you squash the changes please? (or remove the merge commit)
* can you rebase on top of current master please? There were some pipeline fixes that should make the tests go green :)

**Comment by dunmaksim** [comment]
1. All my commits are squashed into one.
2. `master` branch on my fork is updated. This branch is rebased over him.
3. Local run `npm run lint:po` is success:

    ```text
    > ansible-hub-ui@0.1.0 lint:po
    > lint-po locale/*.po
    ```

How to run additional checks locally for quality improvements?

**Comment by himdel** [comment]
Thanks, I have to trigger the workflow manually for new contributors,
looks like `npm run prettier` should fix the `pr-checks` issue,
maybe also run `npm run gettext:extract && npm run gettext:compile`, it should auto-run over the weekend but looks like it doesn't match now.
And Cypress is likely to pass, I'll try to restart any random failures :)

**Comment by dunmaksim** [comment]
Hello, @himdel !

Thanks for your answers!

Me run manually `npm run prettier` and other commands from your commentary. PR is updated.

**Comment by himdel** [comment]
Thanks for doing all that!
This is now ready to be merged, don't worry about the screenshots test, that's expected, I'll take it from here :)

**Pull request merged**
