### PR TITLE
enable ephemeral pr_check.sh

### PR DESCRIPTION
**Pull request by drodowic**
Description:
----------------
* adds pr_check.sh, ci.sh, and build_deploy.sh scripts 
 
Builds a container for use with the frontend operator, and spins up an ephemeral environment to test against the backend master branch

Issue: AAH-1598

### CODE REVIEW

**Review by awcrosby — APPROVED** [review]
LGTM

**Comment by himdel** [comment]
> In the meantime, we thought it could be good to merge this now, which makes this CI check always green, so you don't continue seeing the red X on all your PRs.

Thanks, that sounds sane, approved :+1: 

Just wanted to know what to expect really :)

As for the scripts, oh well, we'll get used to it :)

**Review by himdel — APPROVED** [review]

**Review by himdel — APPROVED** [review]

**Comment by himdel** [comment]
Sounds like there was some bad rebase here?

We probably didn't want to merge 11 already merged PRs, careful next time ;)

(That said, sounds like the resulting squashed commit is only changing `build_deploy.sh`, `ci.sh`, `deploy/frontend.yaml` and `pr_check.sh` so presumably that's still the intended effect.)

**Comment by himdel** [comment]
@drodowic It doesn't seem this worked. The check is still failing on all open PRs, including ones created after this was merged.

**Comment by himdel** [comment]
Much appreciated, this time I saw it go green in #2307 .. but it started failing again before #2310 was created and is now failing in #2311 and #2312 as well.. so .. presumably there's a new problem?

**Pull request merged**
