### PR TITLE
Fix layout for user list

### PR DESCRIPTION
**Pull request by MilanPospisil**
User list has different layout in the top pagination and bottom pagination. This PR fix this, so it looks like group list layout.

### CODE REVIEW

**Comment by ZitaNemeckova** [comment]
@jerabekjiri Please review this one.

**Comment by himdel** [comment]
@MilanPospisil can I ask you to include a before & after screenshot in the description for this one?
(For any kind of mainly visual change, it makes UX review easier.)

**Comment by himdel** [comment]
:+1: I'm seeing the same issue also in Approval dashboard

**Comment by himdel** [comment]
OK... @MilanPospisil this fix is going in the opposite direction than we wanted to.

Users & Approval dashboard are the correct ones,
Users had the padding, it was removed in #611 , as per https://issues.redhat.com/browse/AAH-353

Cc @sbuenafe-rh can you confirm please? (We're talking about the top padding above the bottom pagination control.)

**Comment by sbuenafe-rh** [comment]
@himdel yes, that's correct.

@MilanPospisil is the top photo the **After**?

**Comment by MilanPospisil** [comment]
So, lets close this PR and lets do new ones :-) I felt this change was wrong.

**Comment by himdel** [comment]
@MilanPospisil I've added #1248 to the checklist above .. looks like this is still missing a PR for the namespace detail screen?

**Comment by himdel** [comment]
also added https://github.com/ansible/ansible-hub-ui/pull/1255

**Pull request closed without merging**
