### PR TITLE
Path in the collection dependencies does not contains / at the end of the url

### PR DESCRIPTION
**Pull request by MilanPospisil**
Issue: AAH-1973

https://issues.redhat.com/browse/AAH-1973

### CODE REVIEW

**Comment by himdel** [comment]
(the issue is insights-only, removing backport labels)

**Comment by himdel** [comment]
:+1: definitely works, but if we can get away with `formatPath` always returning a trailing slash, that'd be a better solution, as none of these urls are generated with a trailing slash by default. Looking into whather that is something we can do.. :hourglass:

**Comment by MilanPospisil** [comment]
> 👍 definitely works, but if we can get away with `formatPath` always returning a trailing slash (or always in insights mode), that'd be a better solution, as none of these urls are generated with a trailing slash by default. Looking into whather that is something we can do.. ⌛

That was my first try, but it broke the tests. So it needs more work.

**Review by himdel — APPROVED** [review]
LGTM :+1: 

(assuming tests pass :))

**Pull request merged**
