### PR TITLE
Add test to ensure 'download_concurrency' config is surfaced.

### PR DESCRIPTION
**Pull request by hendersonreed**
This test just verifies that the option exists in the UI - I think that's all the coverage required in the UI tests. Thoughts/opinions/reviews/etcetera from @ZitaNemeckova and @ironfroggy are greatly appreciated.

### CODE REVIEW

**Comment by ZitaNemeckova** [comment]
@hendersonreed It fails sporadically for me on
Screenshot 2020-12-15 at 14 35 59

I think it needs to wait for `http://localhost:8002/ui/repositories?page_size=10&tab=remote` to finish.

**Comment by hendersonreed** [comment]
Good to know - I'll add that wait after standup! Thanks.

**Comment by hendersonreed** [comment]
@ZitaNemeckova I added a wait but that ended up causing a different kind of error. I elected to use `cy.visit` to navigate directly to the repo page - please let me know if you're still seeing intermittent failures - I haven't seen any yet.

**Comment by ZitaNemeckova** [comment]
My remote repos are failed and the test tries to click the `failed` label instead of the kebab
Screenshot 2020-12-16 at 16 22 43

Kebab has a `aria-label="Actions"`. Maybe that will help.

**Comment by hendersonreed** [comment]
@ZitaNemeckova Updated - don't know why I didn't see that aria-label at first. Thanks for working through this with me!

**Comment by ZitaNemeckova** [comment]
LGTM :+1:

**Pull request merged**
