### PR TITLE
Github actions: add linter checks, merge commit check

### PR DESCRIPTION
**Pull request by himdel**
Follow up to #684 

`npm run test-prettier`
previously only did echo, missing semicolon so it didn't run prettier
changed to run a prettier:check task and moved the prettier-but-dont-change-stuff logic there

`npm run lint`
previously tried to run eslint, failed
now runs prettier for js & stylelint for sass

Cypress workflow - move checks for "npm install didn't have to modify package-lock.json" to the new pr-checks workflow.

pr-checks workflow: run linters, npm install check, and check for new merge commits in the PR

---

Also fixed 2 stylelint issues to get green:

    src/components/card-list-switcher/switcher.scss
     5:1  ￼  Expected selector ".icon" to come before selector ".icon:hover"   no-descending-specificity

=> moved `&:hover` style inside `.icon`

    src/containers/search/search.scss
     59:3  ￼  Unexpected duplicate selector ".search-page .pf-c-toolbar__content", first used at line 16   no-duplicate-selectors

=> removed duplicate css, already exists on line 16

### CODE REVIEW

**Comment by himdel** [comment]
Example failure on `package.json` vs `package-lock.json` changes:

https://github.com/ansible/ansible-hub-ui/pull/702/checks?check_run_id=3163760119#step:4:86

**Comment by himdel** [comment]
Example failure on linter issues:

(prettier can't apparently output any errors other than the filename, ignoring until #351 gets merged)

https://github.com/ansible/ansible-hub-ui/pull/702/checks?check_run_id=3163812246#step:4:101

**Comment by himdel** [comment]
Example failure on merge commits:

https://github.com/ansible/ansible-hub-ui/pull/702/checks?check_run_id=3164851079#step:3:14

**Comment by himdel** [comment]
Cc @ZitaNemeckova , should be ready :)

**Review by ZitaNemeckova — APPROVED** [review]

**Pull request merged**
