### PR TITLE
apply partial filter ui

### PR DESCRIPTION
**Pull request by ShaiahWren**
Issue: https://issues.redhat.com/browse/AAH-355

Before:
Screen Shot 2021-07-15 at 11 52 01 AM
After:
Screen Shot 2021-07-15 at 11 51 06 AM

Note: __icontains doesn't work for me, only __contains

### CODE REVIEW

**Comment by himdel** [comment]
```
src/containers/user-management/user-list.tsx
222:      return filterIsSet(params, [
223-        'username',
224-        'first_name',
225-        'last_name',
226-        'email',
227-      ]) ? (
```

you also need to update these to match the new filter names

**Comment by ShaiahWren** [comment]
@himdel Hopefully it's looking better now. :)

**Review by himdel — APPROVED** [review]
LGTM, tested in the UI :+1: :)

**Comment by ShaiahWren** [comment]
Pr closed.

**Pull request merged**
