### PR TITLE
Add spinner to Repo Management

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
Go to Repo Management.

Before:
There's an empty statepage before data loads.
After:
There's a spinner before data loads.

### CODE REVIEW

**Comment by himdel** [comment]
`renderContent` already does do the spinner in both the local & remote branches .. but the empty check was added *before* the loading check in the Remote tab.

So, better fix it there? Or remove the spinner from `renderContent` and keep your change around it?

**Comment by ZitaNemeckova** [comment]
@himdel Thanks :) I removed it from render to make it more consistent with other pages.

**Comment by himdel** [comment]
Makes sense :) But unless github cache is deceiving me, maybe you forgot to push the update? ;)

**Comment by ZitaNemeckova** [comment]
@himdel I didn't even commit it locally 😮  Fixed 😸

**Review by himdel — APPROVED** [review]
LGTM :+1: 

(`itemCount` is only assigned to now, so that could be removed complately, but looks good :))

**Pull request merged**
