### PR TITLE
Change link name

### PR DESCRIPTION
**Pull request by ShaiahWren**
Hi Zita!!
There is one commit for each issue:

https://issues.redhat.com/browse/AAH-548
https://issues.redhat.com/browse/AAH-546
I think I forgot to add 546 before. Lmk if it's ok to keep the commit now.

go to documentation

### CODE REVIEW

**Comment by ZitaNemeckova** [comment]
@ShaiahWren It seems that there's extra commit `change details tabe name and info section header to install`. Please remove it. Otherwise LGTM 👍

**Comment by ShaiahWren** [comment]
HI Zita!
I forgot to include issue#456 in the pr description, my bad. It is now
updated. Now there should be one commit for each issue:
https://issues.redhat.com/browse/AAH-548
https://issues.redhat.com/browse/AAH-546

Is it okay now?

**Review by ZitaNemeckova — APPROVED** [review]
LGTM 👍

**Comment by ShaiahWren** [comment]
pr closed.

**Pull request merged**
