### PR TITLE
Move collection filtering by tags into toolbar

### PR DESCRIPTION
**Pull request by romanblanco**
These changes are part of adjustments related to content sync feature.
The goal of this PR is to move filtering by tags from sidebar into a toolbar together with filtering by name and sync status.

TODO
----------------
- [x] params properties are not restored from URL for tags and sync status
- [x] styling Chip group
- [ ] filtering for Sync can not be applied yet (waiting for https://github.com/ansible/galaxy_ng/issues/45, https://github.com/ansible/galaxy_ng/pull/68)
- [ ] test that the filtering is applied correctly

Links
----------------

* story: https://github.com/ansible/galaxy_ng/issues/17
* subtask https://github.com/ansible/galaxy_ng/issues/19
* [ux mockup](https://marvelapp.com/4dijjai/screen/66793821)

Steps for Testing/QA
-------------------------------

- Go to _Collections_ page in Automation Hub UI
- Toolbar at the top contains the options

### CODE REVIEW

**Comment by romanblanco** [comment]
Current status:

gif

**Comment by sbuenafe-rh** [comment]
One minor fix: can you use sentence case for the tags?

Under the tag dropdown, "Sync Status" should be changed to "**Sync status**"

**Comment by sbuenafe-rh** [comment]
By default, **Sync on** should be selected.

**Comment by romanblanco** [comment]
Current status:
gif2

**Comment by sbuenafe-rh** [comment]
Looks good!

**Pull request closed without merging**
