### PR TITLE
Refactor and reduce flake

### PR DESCRIPTION
**Pull request by hendersonreed**
Summary
-------------

This PR encompasses a number of minor refactorings I developed while getting the Cypress tests to run properly on my machine.

These are:

* minor fixes recommended by ESLint (`let` instead of `var` and quoting recommendations mostly.)
* improved readability of the login, logout, and createUser commands (done with the help of the https://github.com/KabaLabs/Cypress-Recorder Chrome plugin.)
* Removed waiting based on request completion. This seemed to introduce issues - once I stripped that out, things started to work fine.
* added additional options in package.json for running headless cypress against different browsers.

Steps for Testing/QA 
----------------------------
If @ZitaNemeckova can verify that I haven't broken the tests on _her_ end, that'd be great - these changes work on my end.

**note:** these changes are based on the work Zita did in #239. I plan to rebase before merging, so this means that her PR should be merged before this one.

### CODE REVIEW

**Comment by ZitaNemeckova** [comment]
@hendersonreed When I run menu test I see this. It happens sporadically (typing username gets interrupted by requests)
Screenshot 2020-12-09 at 09 44 42

You should add waiting for login and logout to finish to prevent random async problems. Something like this
```
Cypress.Commands.add('logout', {}, () => {
    cy.server();
    cy.route('GET', Cypress.env('prefix') + '_ui/v1/me/').as('me');
    cy.get('[aria-label="user-dropdown"] button').click();
    cy.get('[aria-label="logout"]').click();
    cy.wait('@me');
});
Cypress.Commands.add('login', {}, (username, password) => {
    cy.server();
    cy.route('POST', Cypress.env('prefix') + '_ui/v1/auth/login/').as('login');
    cy.route('GET', Cypress.env('prefix') + '_ui/v1/me/').as('me');
    cy.contains('.pf-c-form__group', 'Username').find('input').first().type(username);
    cy.contains('.pf-c-form__group', 'Password').find('input').first().type(`${password}{enter}`);
    cy.wait('@login');
    cy.wait('@me');
});
```

Otherwise I like it and this can definetely replace #239 so you don't have to rebase :)

**Comment by hendersonreed** [comment]
I went ahead and added the code for waiting on the login requests, and found that it actually caused an error on my end - Cypress can't see the login request happening, and so it times out waiting for it.

image

I'm currently investigating if other people have encountered this issue and if there's a workaround.

**Comment by ZitaNemeckova** [comment]
@hendersonreed Feel free to push that change here if you want me to have a look at it :) (my first guess would be that alias for login has a typo or something but it's hard to tell without code)

**Comment by hendersonreed** [comment]
Hi! So - I have resolved my problem. It was a problem with my `cypress.env.json` :man_facepalming: I didn't have a 'prefix' defined, which meant that those `route()` calls were incorrect. Adding `"prefix":"api/automation-hub/"` to the env file resolved the problems immediately. I still think it's worth committing these changes though, since the refactor is still worth it I think.

With that in mind, I wonder if I should revert my changes to remove the wait on the `@createUser` alias - I'll do whatever you think is right. Currently I don't have any issues with the wait removed, but if it has the potential of causing some flake I can re-introduce the wait.

**Review by ZitaNemeckova — APPROVED** [review]
LGTM :+1:

**Comment by himdel** [comment]
Backporting because #240 depends on this one, which is itself a prerequisite of #301 and #305.

**Pull request merged**
