### PR TITLE
Fix spacing between inputs in Advanced options

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
Fixes https://issues.redhat.com/browse/AAH-285

Before:
Screenshot 2021-05-12 at 11 42 58
After:
Screenshot 2021-05-18 at 10 10 20

@sbuenafe-rh WDYT? Is it enough to show password is not related to proxy url?

### CODE REVIEW

**Comment by himdel** [comment]
(Triggering GH actions to see if tests work..)

**Comment by ZitaNemeckova** [comment]
@rochacbruno WDYT? Is it ok or more visual separation of user/password and proxy url is needed?

**Review by rochacbruno — APPROVED** [review]

**Comment by ZitaNemeckova** [comment]
@himdel A problem I was solving is that `ExpandableSection` overwrites `Form` CSS and inputs get too close together and confuse an user. Adding a `div`  with correct class seemed like elegant fix to have it consistent again.

**Comment by himdel** [comment]
OK, if the idea is just to fix spacing in the expanded section, LGTM :+1:

**Review by himdel — APPROVED** [review]

**Pull request merged**
