### PR TITLE
Use antsibull-docs-ts to render semantic markup

### PR DESCRIPTION
**Pull request by felixfontein**
Uses the TypeScript library [antsibull-docs](https://www.npmjs.com/package/antsibull-docs) (https://github.com/ansible-community/antsibull-docs-ts) to render Ansible markup, including the new semantic markup.

(I marked this as a draft since I want to wait a bit until antsibull-docs-ts reaches 1.0.0 before making this ready.)

FYI, I haven't managed to test this locally, so no idea how the output actually looks...

### CODE REVIEW

**Comment by felixfontein** [comment]
My *guess* is that https://issues.redhat.com/browse/AAH-2156 is the correct issue to reference here. Can someone confirm that? (CC @awcrosby)

**Comment by felixfontein** [comment]
> Does this depend on any backend/importer changes? Or was this just a dev env issue? Can we help? :)

It does not, I simply didn't got around yet to try to run this.

**Comment by felixfontein** [comment]
I tested this with https://github.com/ansible-collections/community.dns/pull/23, and it works! Would be even cooler if `O()` and `RV()` would be turned into links (whenever possible), but I think that's something for a follow-up PR if someone wants to work on this.

**Comment by felixfontein** [comment]
Screenshot of community.dns.hetzner_dns_record (from https://github.com/ansible-collections/community.dns/pull/23) with this PR:
With this PR
Same module rendered with `master` branch:
Without this PR
You can see that `E(...)`, `O(...)`, and `V(...)` aren't interpreted.

**Review by himdel — APPROVED** [review]

**Comment by felixfontein** [comment]
@himdel thanks a lot for reviewing and merging!

While backporting there was a conflict in package-lock.json (where else ;-) ); I've created a manual backport in #3754.

**Pull request merged**
