### PR TITLE
Update groups on My profile to be a Label not an input

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
Fixes-Issue: AAH-160

**Before:**

User is in groups:

Screenshot 2020-12-15 at 14 24 31
Screenshot 2020-12-15 at 14 25 34

User is not in a group:

Screenshot 2020-12-15 at 14 24 55
Screenshot 2020-12-15 at 14 25 10

**After:**

User is in groups:

Screenshot 2020-12-15 at 14 06 14
Screenshot 2020-12-15 at 14 06 24

User is not in a group
Screenshot 2020-12-15 at 14 08 54
Screenshot 2020-12-15 at 14 09 09

@sbuenafe-rh @fionayhlin What do you think? I'm not sure `No groups` looks good.

### CODE REVIEW

**Comment by fionayhlin** [comment]
Hi Zita! The group labels you have on the screenshots should be chips, and it looks like they're missing some padding in between. [No groups] shouldn't be a label -- maybe either leave it blank or use plain text? @sbuenafe-rh 

Also, what's the super user checkbox and who gets to check/uncheck it?

**Comment by sbuenafe-rh** [comment]
@ZitaNemeckova @fionayhlin yep the [No groups] should probably be left blank. 

If the super user checkbox is only read-only and no one can make any edits to this. Then we should just have labels for **Super user** and **User**

**Comment by ZitaNemeckova** [comment]
Updated version:
Screenshot 2020-12-17 at 14 36 03
Screenshot 2020-12-17 at 14 36 29
Screenshot 2020-12-17 at 14 50 59
Screenshot 2020-12-17 at 14 42 45

@sbuenafe-rh @fionayhlin Changed as suggested, please have a look. I just left plain text in Groups if there isn't any group. But I can change it if it looks bad. Thanks for review :)

**Comment by sbuenafe-rh** [comment]
@ZitaNemeckova I think removing the plain text **No groups** and keeping it blank will be okay. And the rest of the changes for the Super user area looks good!

**Review by newswangerd — APPROVED** [review]
LGTM if UX is happy.

**Comment by sbuenafe-rh** [comment]
@ZitaNemeckova @newswangerd LGTM

**Pull request merged**
